# Generated by Django 5.0.4 on 2024-05-12 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_of_offering',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
