# Generated by Django 5.0.4 on 2024-05-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='joid',
        ),
    ]
