# Generated by Django 5.0.4 on 2024-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_date_of_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_of_offering',
            field=models.DateField(),
        ),
    ]
