# Generated by Django 5.0.4 on 2024-05-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('date_applied', models.DateField()),
                ('cover_letter', models.TextField()),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.status')),
            ],
        ),
    ]
