# Generated by Django 5.0.4 on 2024-05-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='jid',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='uid',
            new_name='user',
        ),
    ]
