# Generated by Django 5.0.4 on 2024-05-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_date_of_birth_alter_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='Profile',
            new_name='profile',
        ),
    ]
