# Generated by Django 5.0.4 on 2024-05-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_lid_user_lid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lid_id',
            new_name='lid',
        ),
    ]
