# Generated by Django 5.0.4 on 2024-05-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_lid_id_user_lid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='uid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='uid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='coid',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lid',
            new_name='location',
        ),
    ]
