# Generated by Django 5.0.4 on 2024-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('cover', models.URLField()),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
    ]
