# Generated by Django 5.0.4 on 2024-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AlterField(
            model_name='company',
            name='cover',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(),
        ),
    ]
