# Generated by Django 5.0.4 on 2024-05-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_id',
            new_name='cid',
        ),
    ]
